name        : pkg-config
version     : 0.28
release     : 4
source      :
    - http://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz : 6b6eb31c6ec4421174578652c7e141fdaae2dabad1021f420d8713206ac1f845
homepage    : http://www.freedesktop.org/wiki/Software/pkg-config
license     :
    - GPL-2.0
summary     : manage compile and link flags for libraries
clang       : no
description : |
    pkg-config is a system for managing library compile and link flags that works with automake and autoconf
setup      : |
    %configure --docdir=/usr/share/doc/pkg-config \
               --with-internal-glib
build      : |
    %make
install    : |
    %make_install
