name       : pkg-config
version    : 0.29.2
release    : 9
source     :
    - https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz : 6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591
homepage   : http://www.freedesktop.org/wiki/Software/pkg-config
license    :
    - GPL-2.0
summary    : manage compile and link flags for libraries
component  : system.devel
patterns   :
    - /usr/share/aclocal
description: |
    pkg-config is a system for managing library compile and link flags that works with automake and autoconf
setup      : |
    %configure --docdir=/usr/share/doc/pkg-config \
               --with-internal-glib
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
